const UserTypes = {
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  SET_CURRENT_WORKOUT: "SET_CURRENT_WORKOUT",
  FETCH_USER_START: "FETCH_USER_START",
  FETCH_USER_FINISH: "FETCH_USER_FINISH"
};

export default UserTypes;
