const workoutTypes = {
  CREATE_NEW_WORKOUT: "CREATE_NEW_WORKOUT",
  UPDATE_WORKOUT: "UPDATE_WORKOUT",
  FETCH_WORKOUTS_START: "FETCH_WORKOUTS_START",
  FETCH_WORKOUTS_FINISH: "FETCH_WORKOUTS_FINISH"
};

export default workoutTypes;
